# --- PENGATURAN NAVIGASI HEADER (Menu Laci) ---
header_pages:
  - profil-sekolah.md
  - guru-staf.md
  - kegiatan.md
  - prestasi.md
  - blog.md
  - galeri.md

# TEMA BARU: Mengganti tema bandel dengan tema minimalis.
remote_theme: pages-themes/primer@v0.2.0
plugins:
  - jekyll-remote-theme
